# Generated by Django 4.1 on 2023-12-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wissenswert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ueberschrift_1", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "image_1",
                    models.ImageField(blank=True, upload_to="wissenswert/%Y/%m/%d"),
                ),
                ("text_1", models.TextField(blank=True)),
                ("ueberschrift_2", models.CharField(max_length=200)),
                (
                    "image_2",
                    models.ImageField(blank=True, upload_to="wissenswert/%Y/%m/%d"),
                ),
                ("text_2", models.TextField(blank=True)),
            ],
        ),
    ]
