# Generated by Django 4.1 on 2023-11-04 13:03

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adressen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("address_1", models.CharField(blank=True, max_length=255)),
                ("zip_code", models.IntegerField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("strasse", models.CharField(blank=True, max_length=255)),
                ("hausnummer", models.CharField(blank=True, max_length=5)),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, default="0", max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, default="0", max_digits=9
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "addressen",
            },
        ),
    ]
