# Generated by Django 4.1 on 2023-10-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kollektion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="kollektionen/%Y/%m/%d"),
                ),
            ],
            options={
                "verbose_name": "kollektion",
                "verbose_name_plural": "kollektionen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="rings/%Y/%m/%d")),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rings",
                        to="kollektionen.kollektion",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="kollektion",
            index=models.Index(fields=["name"], name="kollektione_name_04820e_idx"),
        ),
        migrations.AddIndex(
            model_name="ring",
            index=models.Index(fields=["id", "slug"], name="kollektione_id_651276_idx"),
        ),
        migrations.AddIndex(
            model_name="ring",
            index=models.Index(fields=["name"], name="kollektione_name_d215fd_idx"),
        ),
        migrations.AddIndex(
            model_name="ring",
            index=models.Index(
                fields=["-created"], name="kollektione_created_255ead_idx"
            ),
        ),
    ]
