# Generated by Django 4.1 on 2023-12-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kollektionen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kollektion",
            name="text_1",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="kollektion",
            name="text_2",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="kollektion",
            name="text_3",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="kollektion",
            name="text_4",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="kollektion",
            name="ueberschrift_1",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="kollektion",
            name="ueberschrift_2",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="kollektion",
            name="ueberschrift_3",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="kollektion",
            name="ueberschrift_4",
            field=models.CharField(default="", max_length=200),
        ),
    ]
