# Generated by Django 4.1 on 2023-12-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aktuelles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="aktuelles/%Y/%m/%d"),
                ),
                ("beschreibung", models.TextField(blank=True)),
                ("veroeffentlichen", models.BooleanField(default=True)),
                ("termin_von", models.DateTimeField(blank=True)),
                ("termin_bis", models.DateTimeField(blank=True)),
                ("in_stadt", models.CharField(max_length=200)),
                ("plz", models.CharField(max_length=10)),
                ("strasse_hnr", models.CharField(max_length=200)),
                ("ueberschrift", models.CharField(max_length=200)),
            ],
        ),
    ]
