# Generated by Django 4.1 on 2023-11-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atelier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bilderatelier",
            name="image",
            field=models.ImageField(blank=True, upload_to="atelier"),
        ),
    ]
