# Generated by Django 4.1 on 2023-11-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc1", models.FileField(upload_to="pdf/")),
                ("doc2", models.FileField(upload_to="pdf/")),
                ("doc3", models.FileField(upload_to="pdf/")),
            ],
        ),
    ]
